<div class="box" style="width: 700px;">
    <h1 class="box_title">Redigera</h1>

    <div class="box_content">

        <?php
        $this->form->prepare();

        $form = $this->form->get('html-head_fieldset');
        ?>

        <div class="box_content">

            <?php echo $this->partial('form-errors', array('form' => $this->form)); ?>

            <form action="" method="POST" name="company_otm" id="company_otm">
                <label>Namn</label>
                <?php echo $this->formInput($form->get('name')); ?>

                <label>Rubrik</label>
                <?php echo $this->formInput($form->get('title')); ?>

                <label>Beskrivning</label>
                <?php echo $this->formTextarea($form->get('description')); ?>

                <label>Nyckelord</label>
                <?php echo $this->formTextarea($form->get('keywords')); ?>

                <input type="submit" class="button right" value="Spara" style="margin-top: 25px;">
            </form>
            <div class="clear"></div>
        </div>

    </div>
</div>

<div class="box" style="width: 500px;">

    <h1 class="box_title">Tillgänliga variabler</h1>
    <script>
    $(function() {

        $('#test > table > tbody > tr').removeAttr('style');
    })
    </script>
    <div id="test" class="box_content">
        <?php echo $this->partial('mcn/list-available-variables', array('deapth' => 0, 'variables' => $this->page->getVariables())); ?>

        <p>
            Du när du ska använda en varible ska den omringas av %     <br>
            E.g du har variablen first_name då ser de ut <span style="font-weight: bold;">%first_name%</span>
        </p>
    </div>
</div>