<div class="box" style="width: 740px;">
    <h1 class="box_title">List på alla kategorier</h1>

    <div class="box_content">
        <table class="table_rows">
            <thead>
                <tr>
                    <th>Namn</th>
                    <th>Kategori</th>
                    <th>Titel</th>
                    <th>Beskrivning</th>
                    <th>Nyckelord</th>
                    <th>Uppdaterades</th>
                    <th style="width: 30px;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->pages as $page): ?>
                <tr class="<?php echo $this->cycle(array('table_row_dark', ''))->next(); ?>">
                    <td>
                        <?php echo $page->getName(); ?>
                    </td>
                    <td>
                        <?php
                        echo $page->getCategory()
                                  ->getName();
                        ?>
                    </td>
                    <td>
                        <?php echo empty($page['title']) ? 'Nej' : 'Ja'; ?>
                    </td>
                    <td>
                        <?php echo empty($page['description']) ? 'Nej' : 'Ja'; ?>
                    </td>
                    <td>
                        <?php echo empty($page['keywords']) ? 'Nej' : 'Ja'; ?>
                    </td>
                    <td>
                        <?php
                        echo $page->getUpdatedAt()
                                      ->format('Y-m-d H:i:s');
                        ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url('admin/html-head/page/edit', $page->toArray()); ?>">
                            <img src="/images/file_edit.png" alt="Redigera">
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>