<div class="box">
    <h1 class="box_title">Förhandsgranskning av <?php echo $page->getName(); ?></h1>

    <div class="box_content">
        <h2>Rubrik</h2>
        <p>
            <?php echo $this->dynamicHtmlHead()->renderTitle($this->page, $this->page->getTestData()); ?>
        </p>

        <h2>Description</h2>
        <p>
            <?php echo $this->dynamicHtmlHead()->renderDescription($this->page, $this->page->getTestData()); ?>
        </p>

        <h2>Keywords</h2>
        <p>
            <?php echo $this->dynamicHtmlHead()->renderKeywords($this->page, $this->page->getTestData()); ?>
        </p>
    </div>
</div>